  
networks:
  auth_network:
    driver: bridge
    external: true
    name: ${DOCKER_NETWORK}

volumes:
  keycloak_data:
  postgres_data:

services:
  authdb:
    container_name: authdb
    hostname: authdb
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: authserver
      POSTGRES_PASSWORD: authserver
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - auth_network
    platform: linux/arm64 

  keycloak:
    hostname: ${KEYCLOAK_HOSTNAME:-authx.provider.local}
    image: quay.io/keycloak/keycloak:latest
    container_name: authx
    command: start-dev
    ports:
      - 127.0.0.1:9090:8080
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://authdb/auth
      KC_DB_USERNAME: authserver
      KC_DB_PASSWORD: authserver
      KC_HOSTNAME: localhost
    user: "1000:1000" 
    depends_on:
      - authdb
    networks:
      - auth_network
    platform: linux/arm64 
    volumes:
      - keycloak_data:/opt/keycloak/data  