services:
  keycloak:
    hostname: ${KEYCLOAK_HOSTNAME:-authx.provider.local}
    image: quay.io/keycloak/keycloak:26.2.5
    container_name: authx
    command: start-dev
    ports:
      - 127.0.0.1:9090:8080
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    user: "1000:1000" 
    networks:
      - oauth2
    volumes:
      - keycloak_data:/opt/keycloak/data  

networks:
  oauth2:
    external: true
    name: ${DOCKER_NETWORK}

volumes:
  keycloak_data: